### submitting a report
POST http://localhost:3000/reports
content-type: application/json

{
    "make": "toyota",
    "model": "corolla",
    "year": 1980,
    "mileage": 100000,
    "lng": 0,
    "lat": 0,
    "price": 500000
}

### approve existing report
PATCH http://localhost:3000/reports/6
content-type: application/json

{
    "approved": true
}