### create new user
POST http://localhost:3000/auth/signup
content-type: application/json 

{
    "email": "haha@gmail.com", 
    "password": "123"
}

### find a user with a given ID
GET http://localhost:3000/auth/4

### find all users with given email
GET http://localhost:3000/auth?email=haha@gmail.com

### delete a user with a given ID
DELETE http://localhost:3000/auth/654

### updating a user with a given ID
PATCH http://localhost:3000/auth/4
content-type: application/json

{
    "email": "hoho@gmail.com",
    "password": "qosncoi"
}