### signup user
POST http://localhost:3000/auth/signup
content-type: application/json 

{
    "email": "879lice123@gmail.com", 
    "password": "123"
}

### signin user
POST http://localhost:3000/auth/signin
content-type: application/json 

{
    "email": "lice123@gmail.com", 
    "password": "123"
}

### signout user
POST http://localhost:3000/auth/signout

### find a user with a given ID
GET http://localhost:3000/auth/4

### find all users with given email
GET http://localhost:3000/auth?email=haha@gmail.com

### getting current user
GET http://localhost:3000/auth/whoami

### delete a user with a given ID
DELETE http://localhost:3000/auth/5

### updating a user with a given ID
PATCH http://localhost:3000/auth/4
content-type: application/json

{
    "email": "hoho@gmail.com",
    "password": "qosncoi"
}